source("DB.R")

InstitutionNames <- dbGetQuery(db, "select distinct INSTNM from Scorecard order by INSTNM asc")

Cities <- dbGetQuery(db, "select distinct CITY from Scorecard order by CITY asc")

Control <- dbGetQuery(db, "select distinct CONTROL from Scorecard where CONTROL != 'NA' order by CONTROL asc")

trainData <- dbGetQuery(db, "SELECT C150_4 GradRate,year,INSTNM College,COSTT4_A Average_Cost,INC_PCT_LO LowIncome,PAR_ED_PCT_1STGEN FirstGen,SAT_AVG_ALL AvgSat, UGDS, UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI, SAT_AVG,TUITIONFEE_IN,TUITIONFEE_OUT, C150_4_WHITE, C150_4_BLACK, C150_4_HISP, C150_4_ASIAN,  CONTROL,ADM_RATE_ALL, COSTT4_A, PPTUG_EF, UG25abv, PCTFLOAN, AVGFACSAL, INC_PCT_LO, PCTPELL, DEBT_MDN FROM Scorecard WHERE Year = 2011 AND COSTT4_A != 'PrivacySuppressed' AND COSTT4_A IS NOT NULL AND INC_PCT_LO != 'PrivacySuppressed' AND INC_PCT_LO IS NOT NULL AND PAR_ED_PCT_1STGEN != 'PrivacySuppressed' AND PAR_ED_PCT_1STGEN IS NOT NULL AND SAT_AVG_ALL IS NOT NULL AND C150_4 != 'PrivacySuppressed' AND UGDS IS NOT NULL AND UGDS_WHITE IS NOT NULL AND UGDS_BLACK IS NOT NULL AND UGDS_HISP IS NOT NULL AND UGDS_ASIAN IS NOT NULL AND UGDS_AIAN IS NOT NULL AND UGDS_NHPI IS NOT NULL AND  SAT_AVG IS NOT NULL AND TUITIONFEE_IN IS NOT NULL AND TUITIONFEE_OUT IS NOT NULL AND C150_4 IS NOT NULL AND C150_4_WHITE IS NOT NULL AND C150_4_BLACK IS NOT NULL AND C150_4_HISP IS NOT NULL AND C150_4_ASIAN IS NOT NULL AND CONTROL IS NOT NULL AND ADM_RATE_ALL IS NOT NULL AND COSTT4_A IS NOT NULL AND PPTUG_EF IS NOT NULL AND UG25abv IS NOT NULL AND PCTFLOAN IS NOT NULL AND AVGFACSAL IS NOT NULL AND INC_PCT_LO IS NOT NULL AND PCTPELL IS NOT NULL AND DEBT_MDN AND PREDDEG = 'Predominantly bachelor''s-degree granting' ORDER BY INSTNM ASC")

